location               = "eastus"
rg_name                = "rg-ai-lz-demo"
vnet_name              = "vnet-ai-demo"
storage_name           = "aistoragedemo1234567"
ai_foundry_name        = "demo-aifoundry"
