location               = "eastus"
rg_name                = "rg5-ai-lz-demo"
vnet_name              = "vnet5-ai-demo"
storage_name           = "aistoragedemo123456789"
ai_foundry_name        = "demo5-aifoundry"
