location               = "eastus"
rg_name                = "rg01-ai-lz-demo"
vnet_name              = "vnet01-ai-demo"
storage_name           = "aistoragedemo000001"
ai_foundry_name        = "demo01-aifoundry"
